version: '3.8'

services:
  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  order-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  product-db:
    image: mongo:7
    ports:
      - "27017:27017"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
    depends_on:
      - user-db

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_MONGODB_URI: mongodb://product-db:27017/productdb
    depends_on:
      - product-db

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      CLIENTS_USER_SERVICE_URL: http://user-service:8081
      CLIENTS_PRODUCT_SERVICE_URL: http://product-service:8082
    depends_on:
      - order-db
      - product-service
      - user-service