apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.minikube.internal:5433/userdb
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=75
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 384Mi